persona_index:
    path:     /
    defaults: { _controller: "AppBundle:Persona:index" }
    methods:  GET

persona_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Persona:show" }
    methods:  GET

persona_new:
    path:     /new
    defaults: { _controller: "AppBundle:Persona:new" }
    methods:  [GET, POST]

persona_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Persona:edit" }
    methods:  [GET, POST]

persona_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Persona:delete" }
    methods:  DELETE
