#easy admin
easy_admin:
#    disabled_actions: ['delete']
    site_name: 'HCD - Posadas'
    show:
        max_results: 20
    list:
        actions:
            - { name: 'show', icon: 'eye', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
#            - { name: 'delete', icon: 'trash', label: '' }

    design:
        brand_color: '#17a867'
        form_theme: ['horizontal']
        menu:
            - { label: 'Sesión', entity: Sesion }
            - { label: 'Proyecto BAE', entity: ProyectoBAE }
            - { label: 'Moción', entity: Mocion }
            - { label: 'Periodo Legislativo', entity: PeriodoLegislativo }
            - Documento
            - Parametro
            - Expediente
            - Dictamen
            - { label: 'Tipo Expediente', entity: TipoExpediente }
            - { label: 'Tipo Proyecto', entity: TipoProyecto }
            - { label: 'Tipo Decreto', entity: TipoDecreto }
            - { label: 'Tipo Mayoría', entity: TipoMayoria }
            - { label: 'Tipo Tipo Orden de Pago', entity: TipoOrdenPago }
            - Iniciador
            - { label: 'Area Administrativa', entity: AreaAdministrativa }
            - Bloque
            - Comision
            - Cargo
            - Dependencia
            - Persona
            - { label: 'Tipo Relación Persona', entity: TipoRelacionPersona }
            - { label: 'Usuarios', entity: Usuario }
        assets:
            favicon: 'favicon.ico'
#
    assets:
        css:
#            - 'bundles/app/css/admin.css'
        js:
#            - 'build/app.js'
#TODO fix quorum button
