easy_admin:
    entities:
        Usuario:
            class: UsuariosBundle\Entity\Usuario
            list:
                fields:
                    - { property: 'username' }
                    - { property: 'email' }
                    - { property: 'enabled' }
                    - { property: 'lastLogin' }
            form:
                fields:
                    - username
                    - email
                    - enabled
#                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_CONCEJAL': 'ROLE_CONCEJAL', 'ROLE_MESA_ENTRADA': 'ROLE_MESA_ENTRADA' } } }
